#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

biome check --staged --write --files-ignore-unknown=true --no-errors-on-unmatched
git update-index --again
tsc --noEmit -p ./tsconfig.app.json
