name: Update Graypaper

on:
  workflow_dispatch:
  schedule:
    - cron: "51 13 * * *" # using an arbitrary time to avoid high traffic

jobs:
  check_for_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      has_updates: ${{steps.remote_release.outputs.VERSION != steps.local_release.outputs.VERSION}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: What's the latest graypaper-archive version?
      id: remote_release
      run: |
        echo "VERSION=$(gh api /repos/FluffyLabs/graypaper-archive/releases/latest | jq -r '.tag_name')" >> "$GITHUB_OUTPUT"
    - name: What's the version we're using?
      id: local_release
      run: |
        cd graypaper-archive
        echo "VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
  update:
    runs-on: ubuntu-latest
    needs: check_for_updates
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    if: needs.check_for_updates.outputs.has_updates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Get the latest graypaper-archive
        id: archive_update
        run: |
          git submodule update --remote --recursive
          cd graypaper-archive
          echo "VERSION=v$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
          echo "TAG_NAME=$(date +\"%Y-%m-%d\")" >> "$GITHUB_OUTPUT"
          cd ..
      - name: Commit changes to the main branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Bump to ${{steps.archive_update.outputs.VERSION}}
          tag: ${{steps.archive_update.outputs.TAG_NAME}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.archive_update.outputs.TAG_NAME }}
          release_name: Release ${{ steps.archive_update.outputs.TAG_NAME }}
          body: Bumped Graypaper version to ${{steps.archive_update.outputs.VERSION}}
          draft: false
          prerelease: false
