name: Update Graypaper

on:
  schedule:
    - cron: "51 * * * *" # using an arbitrary minute to avoid high traffic

jobs:
  check_for_updates:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      local_version: ${{steps.local_version.outputs.VERSION}}
      remote_version: ${{steps.remote_version.outputs.VERSION}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Check local version
      id: local_version
      run: echo "VERSION=$(cat graypaper-archive/graypaper/VERSION)" >> "$GITHUB_OUTPUT"
    - name: Get latest graypaper and compare versions
      id: remote_version
      run: |
        git submodule update --remote --recursive
        echo "VERSION=$(cat graypaper-archive/graypaper/VERSION)" >> "$GITHUB_OUTPUT"
  update:
    runs-on: ubuntu-latest
    needs: check_for_updates
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    if: needs.check_for_updates.outputs.local_version != needs.check_for_updates.outputs.remote_version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Get latest graypaper-archive and create a pull request
        id: graypaper_update
        run: |
          git submodule update --remote --recursive
          echo "VERSION=v$(cat graypaper-archive/graypaper/VERSION)" >> "$GITHUB_OUTPUT"
      - name: Commit changes to the main branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Bump to ${{steps.graypaper_update.outputs.VERSION}}
          tag: ${{steps.graypaper_update.outputs.VERSION}}
