# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Links check build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/links-check
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"
    - run: npm ci
      working-directory: './'
    - run: npm ci
    - run: npm run qa --if-present
    - run: npm run build --if-present
    - run: npm test --if-present
