name: Publish links-check and links-metadata

on:
  # Deploy on release
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent publish
concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          # required for proper publish authorization
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: npm ci
      - name: Build links-metadata
        working-directory: ./shared/links-metadata
        run: npm run build && npm run update-main
      - name: Build links-check
        working-directory: ./tools/links-check
        run: npm run build
      - name: Publish links-metadata
        run: npm publish --access public
        working-directory: ./shared/links-metadata
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish links-check
        run: npm publish --access public
        working-directory: ./tools/links-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
